/* The seven platform capabilities shown in the Features showcase.
   `media` drives which visual FeatureMedia renders:
     "trailer"                → play UI with a progress bar
     { icon, shape }          → a glyph badge (round-sq | circle)
     { stat, label }          → a big number
     { stars }                → a star rating row
   `image` is a locally hosted, art-directed AI backdrop; `opacity` dims it
   behind the interface treatment. */
export const FEATURES = [
  {
    num: "01",
    tab: "Text-to-Trailer AI",
    tag: "AI · Video",
    title: "Text-to-Trailer AI",
    italic: "30-second visual pitch from your script.",
    desc: "Ckript turns your written script into a captivating 30-second visual trailer. By blending stock footage with AI-generated visuals, your concept reaches producers and investors quickly, clearly, and memorably.",
    bullets: ["Auto-generate trailers in seconds", "Hook decision-makers visually", "5× your discovery rate"],
    image: "/landing/ai/feature-trailer.webp",
    opacity: 0.78,
    media: "trailer",
  },
  {
    num: "02",
    tab: "Locked Ideas, Paid Unlocks",
    tag: "Monetisation",
    title: "Locked Ideas, Paid Unlocks",
    italic: "Public summaries, protected scripts.",
    desc: "Your full script stays safely behind a paywall. Share a curated public summary to spark interest while producers pay to unlock the full work — your IP stays yours, always.",
    bullets: ["Full script IP protection", "Earn from every unlock", "Public teasers drive demand"],
    image: "/landing/ai/feature-lock.webp",
    opacity: 0.7,
    media: { icon: "lock", shape: "round-sq" },
  },
  {
    num: "03",
    tab: "Smart Matching Engine",
    tag: "AI · Discovery",
    title: "Smart Matching Engine",
    italic: "Data-driven, targeted discovery.",
    desc: "Our recommendation engine analyzes producer activity and preferences to surface the right matches. Writers get found by producers actively looking for stories in their genre.",
    bullets: ["Auto-matched by genre & style", "Effortless connections", "Real-time producer alerts"],
    image: "/landing/ai/feature-match.webp",
    opacity: 0.7,
    media: { icon: "search", shape: "circle" },
  },
  {
    num: "04",
    tab: "Script Validation & Scoring",
    tag: "AI · Analysis",
    title: "Script Validation & Scoring",
    italic: "AI-powered story analysis.",
    desc: "Every script gets analyzed for structure, originality, market potential, and narrative quality. You receive a detailed score breakdown — clear insight into what's working and what needs polish, before it reaches the industry.",
    bullets: ["Detailed AI score report", "Structure & originality analysis", "Market-fit recommendations"],
    image: "/landing/ai/feature-score.webp",
    opacity: 0.7,
    media: { stat: "92", label: "Ckript Score" },
  },
  {
    num: "05",
    tab: "Option Hold Exclusivity",
    tag: "Business",
    title: "Option Hold Exclusivity",
    italic: "30-day paid holding periods.",
    desc: "Producers can secure temporary exclusivity by paying to reserve a script for 30 days. Creators get protection and guaranteed compensation during the evaluation window — everyone wins.",
    bullets: ["Guaranteed income per hold", "Exclusive 30-day lock-in", "Faster producer decisions"],
    image: "/landing/ai/feature-hold.webp",
    opacity: 0.7,
    media: { stat: "30", label: "Days exclusive" },
  },
  {
    num: "06",
    tab: "AI Writing Studio",
    tag: "AI · Writing",
    title: "AI Writing Studio",
    italic: "An AI co-writer at your side.",
    desc: "Create, edit, and refine your scripts directly on the platform with an AI writing assistant. Get live guidance on dialogue, pacing, and structure — polish your screenplay before you ever submit.",
    bullets: ["Real-time AI co-writing", "Dialogue & pacing suggestions", "In-platform draft management"],
    image: "/landing/ai/feature-studio.webp",
    opacity: 0.72,
    media: { icon: "edit", shape: "round-sq" },
  },
  {
    num: "07",
    tab: "Expert Reader Reviews",
    tag: "Review",
    title: "Expert Reader Reviews",
    italic: "Curated industry professionals.",
    desc: "Submissions are reviewed by hand-picked expert readers who provide industry-standard coverage reports. Get the same kind of feedback decision-makers use to evaluate scripts every day.",
    bullets: ["Industry-standard coverage", "Hand-picked reviewers", "Actionable professional feedback"],
    image: "/landing/ai/feature-review.webp",
    opacity: 0.72,
    media: { stars: 4 },
  },
];
