import { useState } from "react";
import api from "../../../services/api";
import { getContentTypeFromFormat } from "../lib/format";

/**
 * Owns the wizard's AI-assist actions: generating a prose sample from the
 * script text, and generating a single metadata field (logline / synopsis /
 * roles) by parsing the project content. Reads the editor text getter and the
 * relevant wizard state as args and writes results back through the parent's
 * setters.
 */
export function useAiGeneration({
  editor,
  getEditorPlainText,
  scriptId,
  title,
  formData,
  setFormData,
  setRoles,
  setPublishingDetails,
  setSaved,
  setError,
  enforceGoldPlan,
}) {
  const [proseLoading, setProseLoading] = useState(false);
  const [metaLoadingField, setMetaLoadingField] = useState("");
  const [metaNotice, setMetaNotice] = useState({ field: "", text: "" });

  const handleProseClick = () => {
    if (!editor) return;
    const plainText = getEditorPlainText();
    if (!plainText || plainText.length < 50) {
      setError("Write at least 50 characters of script text before generating a prose sample.");
      return;
    }
    handleGenerateProse();
  };

  const handleGenerateProse = async () => {
    if (!editor) return;
    const plainText = getEditorPlainText();
    if (!plainText) return;

    setProseLoading(true);
    setError("");

    try {
      const { data } = await api.post("/ai/prose-sample", { text: plainText });
      const generatedProse = data?.proseSample?.trim();

      if (generatedProse) {
        setPublishingDetails(prev => ({ ...prev, proseSample: generatedProse }));
        setSaved(false);
      }

    } catch (err) {
      const msg = err.response?.data?.message || "Failed to generate prose sample.";
      setError(msg);
    } finally {
      setProseLoading(false);
    }
  };

  // Generate a single section (logline / synopsis / roles) by parsing the project content with AI
  const handleGenerateMetadata = async (field) => {
    if (!enforceGoldPlan()) return;
    if (!scriptId) return;
    if (!editor || metaLoadingField) return;
    const plainText = getEditorPlainText();
    if (!plainText || plainText.length < 50) {
      setError("Write at least 50 characters of script content before generating with AI.");
      return;
    }

    setMetaLoadingField(field);
    setMetaNotice({ field: "", text: "" });
    setError("");

    try {
      const { data } = await api.post("/ai/generate-metadata", {
        text: plainText,
        fields: [field],
        title,
        primaryGenre: formData.primaryGenre,
        contentType: getContentTypeFromFormat(formData.format),
      });

      let filled = false;
      if (field === "logline" && typeof data.logline === "string" && data.logline.trim()) {
        setFormData((f) => ({ ...f, logline: data.logline.trim().slice(0, 500) }));
        filled = true;
      }
      if (field === "synopsis" && typeof data.synopsis === "string" && data.synopsis.trim()) {
        setFormData((f) => ({ ...f, synopsis: data.synopsis.trim() }));
        filled = true;
      }
      if (field === "roles" && Array.isArray(data.roles) && data.roles.length) {
        setRoles(data.roles.map((role) => ({
          characterName: role.characterName || "",
          type: role.type || "",
          description: role.description || "",
          gender: role.gender || "Any",
          ageRange: {
            min: role.ageRange?.min ?? "",
            max: role.ageRange?.max ?? "",
          },
        })));
        filled = true;
      }

      setSaved(false);
      if (data.usedFallback) {
        setMetaNotice({ field, text: "AI is busy right now — please try again in a moment." });
      } else if (filled) {
        setMetaNotice({ field, text: "Generated by AI — review and edit before submitting." });
      } else {
        setMetaNotice({ field, text: "Not enough story detail — add more script content and try again." });
      }
    } catch (err) {
      setError(err.response?.data?.message || "Failed to generate. Please try again.");
    } finally {
      setMetaLoadingField("");
    }
  };

  return {
    proseLoading,
    setProseLoading,
    metaLoadingField,
    setMetaLoadingField,
    metaNotice,
    setMetaNotice,
    handleProseClick,
    handleGenerateProse,
    handleGenerateMetadata,
  };
}
