import User, { createReferralCode } from "../models/User.js";

/**
 * The user's referral code, minting one if they don't have it yet.
 *
 * Most existing accounts have none: the code is generated by a pre-validate hook that only runs on
 * save, so anyone created before that hook landed has an empty field. Without this, the referral
 * drive would show a broken link to the majority of users. The unique index is the real arbiter —
 * on a collision we simply try again.
 */
export const ensureReferralCode = async (user) => {
  if (user?.referralCode) return user.referralCode;
  if (!user?._id) return "";

  for (let attempt = 0; attempt < 8; attempt += 1) {
    const candidate = createReferralCode();
    try {
      // Conditional on the field still being empty, so two concurrent calls can't both assign.
      const updated = await User.findOneAndUpdate(
        { _id: user._id, $or: [{ referralCode: null }, { referralCode: { $exists: false } }] },
        { $set: { referralCode: candidate } },
        { new: true },
      ).select("referralCode");
      if (updated?.referralCode) return updated.referralCode;

      // Someone else won the race — use whatever they set.
      const current = await User.findById(user._id).select("referralCode");
      if (current?.referralCode) return current.referralCode;
    } catch (error) {
      if (error?.code !== 11000) throw error;   // anything but a duplicate key is a real failure
    }
  }
  return "";
};

/**
 * Competition referral drive: writers who bring other writers into a challenge earn tiered rewards.
 *
 * Scoped by TIME, not by a per-competition counter, so it needs no new bookkeeping on the referrer:
 * a referral counts if the referred account was linked between the competition's registration
 * opening and its submission deadline.
 *
 * Two deliberate constraints, both learned from the existing referral code:
 *
 *  1. Rewards are BADGES and SUBSCRIPTION time only. The legacy `awardReferralBonusForUser` increments
 *     `credits.balance`, a path that does not exist on the User schema — Mongoose strict mode discards
 *     it silently, so every referral bonus ever "awarded" was worth nothing. Until that field exists
 *     and something spends it, granting credits here would be theatre.
 *  2. A referral only counts once the referred account is VERIFIED (`hasReceivedReferralBonus` is the
 *     existing marker for that). Counting unverified signups would make the drive trivially farmable.
 */

export const REFERRAL_TIERS = [
  { count: 3, id: "challenge_referral_bronze", label: "Challenge Advocate", days: 0 },
  { count: 5, id: "challenge_referral_silver", label: "Challenge Champion", days: 15 },
  { count: 10, id: "challenge_referral_gold", label: "Challenge Ambassador", days: 30 },
];

/** The window a referral must fall inside to count toward a competition. */
export const referralWindow = (competition) => ({
  start: competition?.dates?.regOpensAt ? new Date(competition.dates.regOpensAt) : null,
  end: competition?.dates?.endsAt ? new Date(competition.dates.endsAt) : null,
});

/**
 * How many verified referrals this user made during the competition window.
 *
 * Counts on `referredAt` — the moment the link was recorded. `referralBonusAwardedAt` would date the
 * referral to email verification instead, which can land days later and outside a 48-hour event.
 */
export const countCompetitionReferrals = async (userId, competition) => {
  const { start, end } = referralWindow(competition);
  if (!start || !end) return 0;

  return User.countDocuments({
    referredBy: userId,
    hasReceivedReferralBonus: true,
    referredAt: { $gte: start, $lte: end },
  });
};

/** The tier reached at a given count, or null. */
export const tierFor = (count) =>
  [...REFERRAL_TIERS].reverse().find((tier) => count >= tier.count) || null;

/**
 * Progress for the dashboard: current count, the tier earned, and what the next one needs.
 */
export const getReferralProgress = async (userId, competition) => {
  const count = await countCompetitionReferrals(userId, competition);
  const earned = tierFor(count);
  const next = REFERRAL_TIERS.find((tier) => count < tier.count) || null;

  return {
    count,
    earned: earned ? { id: earned.id, label: earned.label } : null,
    next: next ? { label: next.label, needed: next.count - count, at: next.count } : null,
    tiers: REFERRAL_TIERS.map(({ id, label, count: at, days }) => ({ id, label, at, days })),
  };
};

export default getReferralProgress;
